//
//  BString.swift
//  farh
//
//  Created by Yousef on 10/22/18.
//  Copyright © 2018 Ismael AlShabrawy. All rights reserved.

import UIKit


open class BString {
    
    static var language : String = Locale.current.languageCode ?? AR {
        didSet {
            if language.contains(AR) {
                Language.setAppLanguage(lang: AR)
            }else{
                Language.setAppLanguage(lang: En)
            }
        }
    }
    
    class func getText(stringKey : String) -> String {
        var text = ""
        if Language.currentLanguage().contains(AR) {
            text = dectionaryAR[stringKey] ?? ""
        }else{
            text = dectionaryEN[stringKey] ?? ""
        }
        return text
    }
    
    private static let dectionaryAR : [ String : String ] =
        [
            "Example" : "مثال",
            "login" : "تسجيل دخول",
            "menu": "القائمة",
            "sessions": "الجلسات",
            "facebookLogin": "تسجيل دخول عبر الفيس بوك",
            "googleLogin": "تسجيل دخول عبر جوجل",
            "registerText": "ليس لديك حساب؟ ،تسجيل عضوية",
            "email": "البريد الكتروني",
            "password": "كلمة السر",
            "forgetPassword": "نسيت كلمة السر؟",
            "register": "تسجيل عضوية",
            "Empty Email": "من فضلك ادخل البريد الالكتروني.",
            "Empty Password": "من فضلك ادخل كلمة السر",
            "InvalidEmail": "من فضلك ادخل بريد الكتروني صحيح",
            "Invalid Password": "يجب ان تكون كلمة السر اكثر من ٦ حروف",
            "username": "الاسم",
            "phone": "رقم الهاتف",
            "confirmPassword": "تأكيد كلمة السر",
            "gender": "النوع",
            "dateOfBirth": "تاريخ الميلاد",
            "Empty Phone": "من فضلك ادخل رقم الهاتف",
            "Invalid Phone": "من فضلك ادخل رقم هاتف صحيح",
            "male": "ذكر",
            "female":"انثي",
            "networkError": "يوجد خطأ بالشبكة",
            "invalidConfirmPassword": "تأكيد كلمة السر غير صحيحة",
            "symptoms": "اعراض",
            "showMore": "عرض التفاصيل",
            "chatHistory": "تاريخ المحادثة",
            "followup": "متابعة",
            "showLess": "اخفاء التفاصيل",
            "recommendatoin": "روشتة",
            "rateAndReview":  "التقييم و التعليقات",
            "year": "سنة",
            "month": "شهر",
            "day": "يوم",
            "hours": "ساعة",
            "minute": "دقيقة",
            "getConsultation": "استشارة",
            "firstWelcomingText": "مرحبا",
            "secondWelcomingText": "هل تشعر بتحسن اليوم؟",
            "anySymptoms": "الاعراض",
            "anyAttachment": "المتعلقات",
            "emptyResult": "لا يوجد نتائج لهذه الكلمة",
            "ago": "مضت",
            "loginFirst": "يرجي تسجيل الدخول",
            "hateWaiting": "هل مللت من الانتظار بالعيادات؟",
            "estsharaHelpIntro": "استشارة يساعدك في الحصول علي ارشادات طبية مع متخصصين",
            "getStarted": "ابدا الان",
            "bio": "نبذة عنك",
            "haveClinic": "هل لديك عيادة",
            "yes": "نعم",
            "no": "لا",
            "clinicLocation": "مكان العيادة بالتفصيل",
            "syndicate": "صورة النقابة",
            "certificate": "الشهادات الموثقة",
            "submit": "استمرار",
            "completeProfile": "اكمال الملف الشخصي",
            "insertClinicLocation": "من فضلك ادخل عنوان العيادة الخاصة بك ",
            "insertSyndicate": "من فضلك ادخل صورة كارت النقابة",
            "insertCertificate": "من فضلك ادخل صور شهاداتك",
            "addMore": "اضافة المزيد",
             "uploadCertificates": "رفع الشهادات",
             "noConsultation": "لا يوجد استشارات الي الان",
             "uploadSyndicatePlaceHolder": "رفع الشهادات",
             "or": "أو",
             "doctorAvailability": "سيتم الرد عليك خلال",
             "cancel": "الغاء",
             "tooLargeFile": "مساحة هذا الملف كبيرة ، من فضلك اختر ملف اخر",
             "sendRequest": "ارسال طلب",
             "startTyping": "ابدا بالكتابة",
             "doctorAnsweringText": "سيتم مكالمتك في لحظات",
             "emailExists": "هذا البريد موجود بالفعل",
             "phoneExists": "هذا الرقم موجود بالفعل",
             "phoneOrEmailAlreadyExists": "هذا البريد او رقم الهاتف موجود بالفعل",
             "noSymptoms": "ليس مزود باعراض",
             "history": "الماضية",
             "upcoming": "القادمة",
             "accept": "موافق",
             "reject": "رفض",
             "callSuccess": "تم القبول",
             "proccessing": "جار تنفيذ طلبك",
             "conversationStarting": "ستبدأ المحادثة خلال ثوان",
             "calling": "جار المحادثة",
             "sendRecommendation": "ارسال روشتة",
             "diseasesText": "الامراض",
             "allergiesText": "الحساسية",
             "medicationsText": "الأدوية",
             "noDiseases": "لا يوجد امراض",
             "noAllergies": "لا يوجد حساسية",
             "noMedications": "لا يوجد ادوية",
             "writeRecommendation": "اكتب الروشتة",
              "recommendationDone": "تم ارسال الروشتة بنجاح",
              "insertRecommendation": "من فضلك ادخل تفاصيل الروشتة",
              "processingCall": "انتظر حتي انتهاء الاستشارة الحالي",
              "signout": "تسجيل خروج",
              "thanksForEstshara": "شكرا لاستخدامكم استشارة",
              "rateDoctor": "قيم الطبيب",
              "writeComment": "اكتب تعليق",
              "addImage": "اضف صور",
              "addFiles": "اضف ملفات",
              "failedToSend": "خطأ بالارسال",
              "resened" : "اعادة الارسال",
              "online": "متاح",
              "typing": "يكتب...",
              "endChat": "انهاء المحادثة",
              "enterMessage": "ادخل رسالتك",
              "timeLeft": "الوقت المتبقي المحادثة",
              "endChatConfirmation": "هل تريد انهاء المحادثة؟",
              "otherUserEndsChat":"انهي المحادثة",
              "doctor": "الطبيب",
              "patient": "المريض",
              "timeIsOut": "عذرا تم الانتهاء من الوقت.",
              "loading": "تحميل...",
              "reload": "اعادة التحميل",
              "myProfile": "الملف الشخضي",
              "addEmpolyer": "اضافة موظف",
              "blog": "مدونة",
              "settings": "الاعدادات",
              "contactUs": "تواصل معنا",
              "termsAndConditions": "الشروط و الاحكام",
              "share": "مشاركة استشارة",
              "supscriptions": "الاشتراكات",
              "medicalInfo": "المعلومات الطبية",
              "add": "اضافة",
              "FAQ": "الاسئلة الشائعة ",
              "aboutUs": "عنا",
              "notification": "الاشعارات",
              "editProfile": "تعديل الملف الشخصي",
              "changePassword": "تعديل كلمة السر",
              "language": "اللغة",
              "updateProfile": "تعديل الملف الشخصي",
              "update": "تعديل",
              "updatedSuccessfully": "تم تعديل البيانات بنجاح.",
              "clinicAddress" : "عنوان العيادة",
              "articles": "المقالات",
              "noArticles": "لا يوجد مقالات.",
              "noClinicAddress" : "لا يوجد عنوان",
              "noCertificates" : "لا يوجد شهادات",
              "deleteArticleConfirmation": "هل تريد حذف هذا المقال؟",
              "waitTillEnd": "من فضلك انتظر",
              "addCertificates": "اضف شهادات",
              "deleteCertificateConfirmation": "هل تريد حذف هذه الشهادة؟",
              "close": "اغلاق",
            "updatingChat": "جار تحديث المحادثة",
            "noConnection": "لا يوجد اتصال بالشبكة",
            "backOnline": "جار التصال باشبكة",
            "diagnoseTheCase": "ما هو تشخيصك للحالة؟",
            "guest": "ضيف",
            "followUpSentence": "سيتم ارسال طلب متابعة للدكتور",
            "proceed": "، استمرار؟",
            "cancelRequestText": "هل تريد انهاء الاستشارة؟",
            "ConsultationCancelationDone": "تم انهاء الاستشارة بنجاح",
            "noAnswer": "عفوا يوجد طبيب متاح الان",
            "expiredSession": "عفوا هذه المحادثة منتهية",
            "messageIndividualExpired": "خطة الدفع الخاصة بك انتهت ، هل ترغب ف التجديد الان؟",
            "messageIndividualUnset": "لم تقم باختيار خطة دفع بعد ، هل ترغب فى الاختيار الان؟",
            "messageCompanyExpired": "خطة الدفع الخاطة بشركتك انتهت ، لا يزال يمكنك الدفع لهذه الاستشارة!",
            "messageLimitReached": "عفوا،، استهلكت اقصى عدد للاستشارات اليومية ،، لا يزال يمكنك الدفع لهذه الاستشارة!",
            "once": "مرة واحدة",
            "monthly": "شهري",
            "annually": "سنوي",
            "privacyPolicyText": "اوافق علي الشروط والاحكام الخاصة باستشارة.",
            "Estshara": "استشارة",
            "confirm": "تأكيد",
            "choosePaymentPlan": "من فضلك اختر خطة الدفع",
            "paymentPlan": "خطة الدفع",
            "withdrawn": "سيتم خصم",
            "eg": "جنيه",
            "finishedConsultationError": "عفوا يبدو ان هناك خطأ بالشبكة، يرجي المحواولة في وقت لاحق",
            "ok": "حسنا",
            "companyFollowText": "انت ضمن خطة دفع مع",
            "startAt": "يبدأ في",
            "endAt": "ينتهي في",
            "expiredAt": "ينتهي في",
            "noPaymentPlan": "لم تشترك في اي خطة دفع بعد",
            "days": "ايام",
            "onceText": "لا يزال لديك استشارة اخري!",
            "renew": "تجديد",
            "setPayment": "انشأ خطة دفع",
            "messageReason": "سبب الرسالة",
            "feedback": "مفترحات",
            "complaint": "شكاوي",
            "yourMessage": "الرسالة",
            "sendMessage": "ارسال",
            "contactUseIntro": "استشارة هي منصة توفر الاستشارات الطبية عبر المكالمات الاونلاين، تهدف لاتاحة الاستشارات للجميع في الشرق الاوسط.",
            "sendMessageIsSuccessfullyDone": "تم ارسال الرسالة بنجاح.",
            "insertMessageError": "من فضلك ادخل الرسالة",
            "firstAboutText": """
            Estshara is a platform that provides healthcare consultation online. aiming to make healthcare consultation accessible to everyone in the MENA region.
            
            helping small companies with their employees health insurance. also sustain an advanced technological growth level in the sector of healthcare.
            """,
            "secondAboutText": "We strive to become the leading healthcare consultation platform in the MENA region..",
            "thirdAboutText": "We aim to help people get the possible medical consultation they need with the easiest ways possible.",
            "forthAboutText": "The idea of estshara developed years ago, behind was our love for telecommunication and the primary goal of saving people’s lives, we united our efforts to build something that is a mix between both our passions, and from there we decided to build a platform to easily connect doctors to their patients, to expand and serve more people in more places and we’re always striving to upgrade and enhance our efforts.",
            "ourVision": "رؤيتنا",
            "ourMission": "مهمتنا",
            "ourStory": "قصتنا",
            "joinCompanyText": """
            Join your company subscription plan, and enjoy
            having consulting calls.
            """,
            "companiesPackage": "باقات الشركات",
            "insertCode": "من فضلك ادخل كود لشركة",
            "joinRequestSuccessfullySend": "تم ارسال طلب الاشتراك بنجاح.",
            "leavingRequestSuccessfullySent": "تم ارسال طلب المغادرة بنجاح.",
            "internetConnectionCheck": "من فضلك تأكد باتصالك بالشبكة.",
            "alreadyJoinedForCompany": "تم الانضمام لخطة الدفع الخاصة بشركة",
            "pendingRequest": "تم تقديم طلبك لشركة",
            "companyId": "Your company ID",
            "insertValidCompanyCode": "من فضلك ادخل كود شركة صحيح!",
            "leaveCompany": "الغاء الاشتراك",
            "pendingLeavingRequest": "تم تقديم طلب لمغادرة شركة",
            "oldPassword": "كلمة السر القديمة",
            "newPassword": "كلمة السر الجديدة",
            "EmptyNewPassword": "من فضلك ادخل كلمة السر الجديدة",
            "passwordChangedSuccessfully": "تم تغيير كلمة السر بنجاح",
            "invalidPasswordText": "كلمة سر غير صحيحة",
            "transactionDoneSuccessfully": "تمت عملية الدفع بنجاح",
            "callingIssue": "حدث خطأ بالاتصال.",
            "back": "عودة",
            "patientCancelCall": "عفوا، يبدو ان المريض لا يستطع الاجابة.",
            "available": "متاح",
            "deactivateTheAccount": "بعد تحويل حسابك الي غير نشط لن تتمكن من استقبال اي استشارات.",
            "accountIsDeactivated": "حسابك غير مفعل",
            "activate": "تفعيل",
            "consultationType": "نوع الحجز",
            "chat": "دردشة",
            "call": "مكالمة",
            "noNotification": "ليس لديك اي اشعارات حاليا",
            "notificationListIsEmpty": "قائمة الاشعارات بالفعل فارغة!",
            "deleteNotificationConfirmation": "هل تريد حذف الاشعارات؟",
            "download": "تحميل الملف",
            "ratingIsDoneSuccessfully": "تم التقييم بنجاح",
            "momentsAgo": "منذ لحظات",
            "doctorInActive": "عفوا ، الطبيب غير متاح الان.",
            "restartingApp": "تغيير اللغة يتطلب اعادة تشغيل التطبيق!",
            "arabic": "اللغة العربية",
            "english": "اللغة الانجليزية",
            "confirmationSignout": "هل تريد تسجيل الخروج؟",
            "newNotifications": "اشعارات جديدة",
            "newConsultations": "استشارات جديدة",
            "acceptingLeave": "قبلت طلبك للمغادرة.",
            "rejectingLeave": "رفضت طلبك للمغادرة.",
            "acceptingJoin": "قبلت طلبك للانضمام.",
            "rejectingJoin": "رفضت طلبك للانضمام.",
            "sendCodeForEmail": "سيتم ارسال رسالة تحقق عبر البريد الالكتروني",
            "confirmChangePassword": "تأكيد تغيير كلمة السر",
            "code": "رمز التأكيد",
            "specialists": "التخصص",
            "insertSpecialists": "من فضلك ادخل تخصصك",
            "addVideo": "اضف فيديو",
            "itSeems": "يبدو ان",
            "notResponding": "لا يستجيب،",
            "noBlogs": "لا يوجد مدونات",
            "notificationDeactivatedSuccessfully": "تم تعطيل الاشعارات بنجاح",
            "deactivateNotificationConfirmation": "هل تريد تعطيل الاشعارات؟",
            "notificationActivatedSuccessfully": "تم تشغيل الاشعارات بنجاح",
            "startNow": "ابدا الان",
            "wantToHelp": "هل تريد مساعدة المرضي؟",
            "exit": "خروج",
            "helloDoc": "مرحبا دكتور",
            "reviseYourData": "يتم مراجعة حسابك الان ...",
            "willBeBack": "سنعود اليك في وقت قصير جدا",
            "video": "فيديو.mp4",
            "doctorCancelCall": "عفوا، يبدو ان الطبيب لا يستطع الاجابة.",
            "wallet": "Wallet",
            "credit": "Credit",
            "walletIdentifier": "Wallet identifier",
            "payBy": "الدفع عن طريق",
            "verify": "تاكيد",
            "wantToLogin": "هل تريد تسجيل الدخول؟",
            "insertToken": "من فضلك ادخل الكود",
            "next": "التالي"
    ]
    
    private static let dectionaryEN : [ String : String ] =
        [
            "Example" : "Example",
            "login" : "Login",
            "menu": "Menu",
            "sessions": "Sessions",
            "facebookLogin": "Continue with Facebook",
            "googleLogin": "Continue with Google",
            "registerText": "Don't have an account?, Sign up.",
            "email": "Email",
            "password": "Password",
            "forgetPassword": "Forgot Password?",
            "register": "Register",
            "Empty Email": "Please insert your email",
            "Empty Password": "Please inset your password",
            "InvalidEmail": "Please insert a valid Email",
            "Invalid Password": "Password should be more than 6 letters",
            "username": "Username",
            "phone": "Phone",
            "confirmPassword": "Confirm Password",
            "gender": "Gender",
            "dateOfBirth": "Date of birth",
            "Empty Phone": "Please insert your phone",
            "Invalid Phone": "Please insert a valid phone number",
            "male": "Male",
            "female":"Female",
            "networkError": "The Network seem to have some error",
            "invalidConfirmPassword": "Confirmation password does not match with the password",
            "symptoms": "Symptoms",
            "showMore": "Show Details",
            "chatHistory": "Chat history",
            "followup": "Follow up",
            "showLess": "Hide details",
            "recommendatoin": "Recommendation",
            "rateAndReview":  "Rate and Review",
            "year": "Year",
            "month": "Month",
            "day": "Day",
            "hours": "Hours",
            "minute": "Minutes",
            "getConsultation": "Get Consultation",
            "firstWelcomingText": "Hello",
            "secondWelcomingText": "feeling good today?",
            "anySymptoms": "Any sypmtoms",
            "anyAttachment": "Add attachment",
            "emptyResult": "No result for this keyword",
            "ago": "ago",
            "loginFirst": "Please login first",
            "hateWaiting": "Hate waiting in clinics!",
            "estsharaHelpIntro": "Eshtshara helps you get cousulting calls with professionals",
            "getStarted": "Get started",
            "bio": "Bio",
            "haveClinic": "Do you have a clinic?",
            "yes": "Yes",
            "no": "No",
            "clinicLocation": "Clinic location in details",
            "syndicate": "Syndicate ID photo",
            "certificate": "Certificates",
            "submit": "Submit",
            "completeProfile": " Complete profile",
            "insertClinicLocation": "Please insert the location of your clinic",
            "insertSyndicate": "Please insert your syndicate",
            "insertCertificate": "Please insert your certificates",
            "addMore": "Add More",
            "uploadCertificates": "Upload certificates",
            "noConsultation": "No consultation in the queue for now!",
            "uploadSyndicatePlaceHolder": "Upload Syndicate",
            "or": "OR",
            "doctorAvailability": "Doctor will be available in",
            "cancel": "Cancel",
            "tooLargeFile": "This file size is too large, please choose smaller file",
            "sendRequest": "Send request",
            "startTyping": "Start typing",
            "doctorAnsweringText": "The doctor is calling you in seconds",
            "emailExists": "Email may exists",
            "phoneExists": "Phone may exists",
            "phoneOrEmailAlreadyExists": "This phone or email already exists",
            "noSymptoms": "No symptoms provided",
            "history": "History",
            "upcoming": "Upcoming",
            "accept": "Accept",
            "reject": "Reject",
            "callSuccess": "Accepted",
            "proccessing": "Processing",
            "conversationStarting": "The coversation is starting in seconds",
            "calling": "Calling",
            "sendRecommendation": "Send recommendation",
            "diseasesText": "Diseases",
            "allergiesText": "Allergies",
            "medicationsText": "Medications",
            "noDiseases": "No Diseases",
            "noAllergies": "No Allergies",
            "noMedications": "No Medications",
            "writeRecommendation": "Write your recomendation",
            "recommendationDone": "Recommendation done successfully",
            "insertRecommendation": "Please insert your recommendation",
            "processingCall": "Wait for ending current consultation",
            "signout": "Singout",
            "thanksForEstshara": "Thanks for using Estshara",
            "rateDoctor": "Rate doctor",
            "writeComment": "Write comment",
            "addImage": "Add Images",
            "addFiles": "Add Files",
            "failedToSend" : "Failed to send",
            "resened" : "Resened",
            "online": "Online",
            "typing": "Typing...",
            "endChat": "End chat",
            "enterMessage": "Enter your message",
            "timeLeft": "Time left for chat",
            "endChatConfirmation": "Do you want to end chat?",
            "otherUserEndsChat":"ends chat",
            "doctor": "The Doctor",
            "patient": "The Patient",
            "timeIsOut": "Sorry the time is out.",
            "loading": "Loading...",
            "reload": "Reload",
            "myProfile": "My Profile",
            "addEmpolyer": "Add Employer",
            "blog": "Blog",
            "settings": "Settings",
            "contactUs": "Contanct Us",
            "termsAndConditions": "Terms and Policies",
            "share": "Share Estshara",
            "supscriptions": "SUBSCRIPTION",
            "medicalInfo": "MEDICAL INFO",
            "add": "Add",
            "FAQ": "FAQ",
            "aboutUs": "About us",
            "notification": "Notification",
            "editProfile": "Edit profile",
            "changePassword": "Change password",
            "language": "Language",
            "updateProfile": "Update profile",
            "update": "Update",
            "updatedSuccessfully": "Updating is successfully done.",
            "clinicAddress" : "Clinic address",
            "articles": "Articles",
            "noArticles": "No articles yet.",
            "noClinicAddress" : "No address provided",
            "noCertificates" : "No certificates",
            "deleteArticleConfirmation": "Do you want to delete this article?",
            "waitTillEnd": "Please wait",
            "addCertificates": "Add Certificates",
            "deleteCertificateConfirmation": "Do you want to delete this certificate?",
            "close": "Close",
            "updatingChat": "Updating conversation",
            "noConnection": "No connection",
            "backOnline": "Back online",
            "diagnoseTheCase": "How would you diagnose the case?",
            "guest": "Guest",
            "followUpSentence": "A follow up request will be sent to ",
            "proceed": ", Continue?",
            "cancelRequestText": "Do you want to cancel this consultation?",
            "ConsultationCancelationDone": "Consultation cancellation done successfully",
            "noAnswer": "Sorry, there are no doctors availabe now!",
            "expiredSession": "Sorry, This session is expired.",
            "messageIndividualExpired": "Your payment plan has expired, would you like to renew it now?",
            "messageIndividualUnset": "You haven\'t setup a payment plan yet, set it up now?",
            "messageCompanyExpired": "You company payment plan has expired, would you like to pay this time on your own?",
            "messageLimitReached": "Sorry you have reached the limits of consultation, would you like to pay for this extra consultation?",
            "once": "Once",
            "monthly": "Monthly",
            "annually": "Annually",
            "privacyPolicyText": "Agree to Estshara privacy policy",
            "Estshara": "Estshara",
            "confirm": "Confirm",
            "choosePaymentPlan": "Please choose payment plan",
            "paymentPlan": "Paymet plan",
            "withdrawn": "withdrawn",
            "eg": "EG",
            "finishedConsultationError": "Sorry! Seemed to have some error with the network, Try again later!",
            "ok": "OK",
            "companyFollowText": "You are following the payment plan of",
            "startAt": "Started At",
            "endAt": "End At",
            "expiredAt": "Expired on",
            "noPaymentPlan": "Your payment plan is unset yet!",
            "days": "Days",
            "onceText": "You still have one extra consultation!",
            "renew": "Renew",
            "setPayment": "Set payment plan",
            "messageReason": "Message reason",
            "feedback": "Feedback",
            "complaint": "Complaint",
            "yourMessage": "Your message",
            "sendMessage": "Send",
            "contactUseIntro": "Estshara is a platform that providers healthcare consultation online. Aiming to make healthcare consultation accessible too everyone in the MENA region.",
            "sendMessageIsSuccessfullyDone": "Your message is successfully sent.",
            "insertMessageError": "Please insert your message",
            "firstAboutText": """
            Estshara is a platform that provides healthcare consultation online. aiming to make healthcare consultation accessible to everyone in the MENA region.
            
            helping small companies with their employees health insurance. also sustain an advanced technological growth level in the sector of healthcare.
            """,
            "secondAboutText": "We strive to become the leading healthcare consultation platform in the MENA region..",
            "thirdAboutText": "We aim to help people get the possible medical consultation they need with the easiest ways possible.",
            "forthAboutText": "The idea of estshara developed years ago, behind was our love for telecommunication and the primary goal of saving people’s lives, we united our efforts to build something that is a mix between both our passions, and from there we decided to build a platform to easily connect doctors to their patients, to expand and serve more people in more places and we’re always striving to upgrade and enhance our efforts.",
            "ourVision": "Our vision",
            "ourMission": "Our mission",
            "ourStory": "Our story",
            "joinCompanyText": """
            Join your company subscription plan, and enjoy
            having consulting calls.
            """,
            "companiesPackage": "Companies package",
            "insertCode": "Please insert company code",
            "joinRequestSuccessfullySend": "The join request is successfully sent.",
            "leavingRequestSuccessfullySent": "The leaving request is successfully sent.",
            "internetConnectionCheck": "Please make sure that you connect network.",
            "alreadyJoinedForCompany": "You\'re following the payment plan of",
            "pendingRequest": "Waiting for response for your request to join",
            "companyId": "Your company ID",
            "insertValidCompanyCode": "Please insert a valid company code!",
            "leaveCompany": "Request leaving",
            "pendingLeavingRequest": "Waiting for response for your request to leave",
            "oldPassword": "Old password",
            "newPassword": "New password",
            "EmptyNewPassword": "Please insert new password",
            "passwordChangedSuccessfully": "Password changed successfully",
            "invalidPasswordText": "This password is incorrect",
            "transactionDoneSuccessfully": "Your payment plan is successfully done",
            "callingIssue": "Sorry something went error with the call.",
            "back": "Back",
            "patientCancelCall": "Sorry, The patient can't take the call now.",
            "available": "Available",
            "deactivateTheAccount": "After deactivating your account,You are not able to recieve any consultations.",
            "accountIsDeactivated": "Your account is deactivated!",
            "activate": "Activate",
            "consultationType": "Constultation type",
            "chat": "Chat",
            "call": "Call",
            "noNotification": "You have no notifications",
            "notificationListIsEmpty": "Notification list is already empty!",
            "deleteNotificationConfirmation": "Do you want to delete the notifications?",
            "download": "Download pdf",
            "ratingIsDoneSuccessfully": "Rating is successfully done",
            "momentsAgo": "moments ago",
            "doctorInActive": "Sorry, Doctor is inactive now",
            "restartingApp": "Change language requires restarting application!",
            "arabic": "Arabic",
            "english": "English",
            "confirmationSignout": "Do you want to logout?",
            "newNotifications": "New notifications",
            "newConsultations": "New consultations",
            "acceptingLeave": "accepted your leaving request.",
            "rejectingLeave": "rejected your leaving request.",
            "acceptingJoin": "accepted your join request.",
            "rejectingJoin": "rejected your join request.",
            "sendCodeForEmail": "A verification code will be sent to your email",
            "confirmChangePassword": "Confirm change password",
            "code": "Code",
            "specialists": "Speciality",
            "insertSpecialists": "Please insert your spexciality",
            "addVideo": "Add videos",
            "itSeems": "It seems",
            "notResponding": "Not responding,",
            "noBlogs": "There are no blogs now",
            "notificationDeactivatedSuccessfully": "The notification is successfully deactivated",
            "deactivateNotificationConfirmation": "Do you want to deactivate the notifications?",
            "notificationActivatedSuccessfully": "The notification is successfully activated",
            "startNow": "Start now",
            "wantToHelp": "Do you want to help patient?",
            "exit": "Exit",
            "helloDoc": "Hello Doctor",
            "reviseYourData": "Your account is being reviewed at the moment...",
            "willBeBack": "We'll get back to you in no time.",
            "video": "Video.mp4",
            "doctorCancelCall": "Sorry, The doctor can't take the call now.",
            "wallet": "Wallet",
            "credit": "Credit",
            "walletIdentifier": "Wallet identifier",
            "payBy": "Pay by",
            "verify": "Verify",
            "wantToLogin": "Do you want to login?",
            "insertToken": "Please insert the code",
            "next": "Next"
    ]

    
}


